# définition des routes de PortfolioRemyArticlesBundle

# nom de la route
portfolioremyarticles_accueil:
    # url de type "/articles/1"
    pattern: /{page}
    # contrôleur défini par le nom du bundle, le nom du contrôleur et la
    # méthode à exécuter (ici index)
    defaults: { _controller: PortfolioRemyArticlesBundle:Articles:index, page: 1 }
    requirements:
      # le paramètre {page} doit être composé uniquement de chiffres
        page: \d*
    
# nom de la route
portfolioremyarticles_voir:
    # url de type "/articles/article/bla-bla"
    pattern: /article/{slug}
    # contrôleur défini par le nom du bundle, le nom du contrôleur et la
    # méthode à exécuter (ici voir)
    defaults: { _controller: PortfolioRemyArticlesBundle:Articles:voir }
    # requirements:
      # le paramètre {id} est composé d'un ou plusieurs chiffres
        # id: \d+

# nom de la route
portfolioremyarticles_ajouter:
    # url de type "/articles/ajouter"
    pattern: /ajouter
    # contrôleur défini par le nom du bundle, le nom du contrôleur et la
    # méthode à exécuter (ici ajouter)
    defaults: { _controller: PortfolioRemyArticlesBundle:Articles:ajouter }

# nom de la route
portfolioremyarticles_modifier:
    # url de type "/articles/modifier/1"
    pattern: /modifier/{id}
    # contrôleur défini par le nom du bundle, le nom du contrôleur et la
    # méthode à exécuter (ici modifier)
    defaults: { _controller: PortfolioRemyArticlesBundle:Articles:modifier }
    requirements:
      # le paramètre {id} est composé d'un ou plusieurs chiffres
        id: \d+

# nom de la route
portfolioremyarticles_supprimer:
    # url de type "/articles/supprimer/1"
    pattern: /supprimer/{id}
    # contrôleur défini par le nom du bundle, le nom du contrôleur et la
    # méthode à exécuter (ici supprimer)
    defaults: { _controller: PortfolioRemyArticlesBundle:Articles:supprimer }
    requirements:
      # le paramètre {id} est composé d'un ou plusieurs chiffres
        id: \d+
        
# nom de la route
portfolioremyarticles_categorie:
    # url de type "/categorie/Expérience"
    pattern: /categorie/{categorie}
    # contrôleur défini par le nom du bundle, le nom du contrôleur et la
    # méthode à exécuter (ici categorie)
    defaults: { _controller: PortfolioRemyArticlesBundle:Articles:categorie}
 
 # nom de la route
portfolioremyarticles_tag:
    # url de type "/tag/Symfony2"
    pattern: /tag/{tag}
    # contrôleur défini par le nom du bundle, le nom du contrôleur et la
    # méthode à exécuter (ici tag)
    defaults: { _controller: PortfolioRemyArticlesBundle:Articles:tag}