parameters:
#    portfolio_remy_articles.example.class: PortfolioRemy\ArticlesBundle\Example

services:
    portfolioremy_articles.antispam:
        class: PortfolioRemy\ArticlesBundle\Antispam\PortfolioRemyAntispam
    
    # intl twig extension
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }