# importation des routes définis dans les bundles
# pour le bundle PortfolioRemyArticlesBundle
portfolio_remy_articles:
    # importation des routes du bundle
    resource: "@PortfolioRemyArticlesBundle/Resources/config/routing.yml"
    # définition du préfix pour les routes ici "/articles"
    prefix: /{_locale}
    defaults: {_locale: fr}
    requirements:
        _locale: en|fr

index:
   pattern: /{_locale}
   defaults: {_controller: PortfolioRemyArticlesBundle:Articles:index, page: 1, _locale: fr}
   requirements:
       _locale: en|fr
   
# nom de la route
portfolioremy_contact:
    # url de type "/contact"
    pattern: /{_locale}/contact
    # contrôleur
    defaults: { _controller: PortfolioRemyArticlesBundle:Contact:contact, _locale: fr }
    requirements:
        _locale: en|fr

portfolioremy_legal:
    # url de type "/contact"
    pattern: /{_locale}/legal
    # contrôleur
    defaults: { _controller: PortfolioRemyArticlesBundle:Articles:legal, _locale: fr }
    requirements:
        _locale: en|fr
    
portfolioremy_feedback:
    pattern: /{_locale}/feedback
    defaults: { _controller: PortfolioRemyArticlesBundle:Contact:feedback, _locale: fr }
    requirements:
        _locale: en|fr

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}
    defaults: { _locale: fr }
    requirements:
        _locale: en|fr

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile
    defaults: { _locale: fr }
    requirements:
        _locale: en|fr

fos_user_registrer:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register
    defaults: { _locale: fr }
    requirements:
        _locale: en|fr

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
    defaults: {locale: fr }
    requirements:
        _locale: en|fr

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile
    defaults: { _locale: fr }
    requirements:
        _locale: en|fr

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /{_locale}/group
    defaults: { _locale: fr }
    requirements:
        _locale: en|fr